FROM harbor.nurilab.pe.kr/azerothcore/ac-wotlk-authserver:master
LABEL org.opencontainers.image.authors="zardkim" \
      org.opencontainers.image.version="1.0.0" \
      org.opencontainers.image.title="AzerothCore WotLK Authserver" \
      org.opencontainers.image.description="Compiled authserver binary with mod-playerbots + 65 custom AzerothCore modules baked in."
