FROM harbor.nurilab.pe.kr/azerothcore/ac-wotlk-worldserver:master
LABEL org.opencontainers.image.authors="zardkim" \
      org.opencontainers.image.version="1.0.0" \
      org.opencontainers.image.title="AzerothCore WotLK Worldserver" \
      org.opencontainers.image.description="Compiled worldserver binary with mod-playerbots + 65 custom AzerothCore modules baked in."
